[package]
id = "terrain"
name = "terrain"
version = "0.0.1"
content = { type = "Asset", schema = true, code = true }

[dependencies]
map = { path = "../map" }

[components.heightmap]
type = { type = "Vec", element_type = "I16" }
name = "Heightmap"
attributes = ["Debuggable"]
description = """
A list of the heights of all of the tile corners in this chunk.

Because this includes tile corners of tiles in neighboring chunks too, the size
of this list is (CHUNK_SIZE + 1) * (CHUNK_SIZE + 1).

The tiles are ordered X- to X+, then Y- to Y+. For reference:
```
 X----->
Y 0 1 2
| 3 4 5
| 6 7 8
V
```
"""

[components.altitude]
type = "F32"
name = "Altitude"
attributes = ["Debuggable"]
description = "The height of this entity on the map above sea level. Computed using map::position."

[components.mesh_positions]
type = { type = "Vec", element_type = "Vec3" }
name = "MeshPositions"
attributes = ["Debuggable"]

[components.mesh_normals]
type = { type = "Vec", element_type = "Vec3" }
name = "MeshNormals"
attributes = ["Debuggable"]

[components.mesh_tangents]
type = { type = "Vec", element_type = "Vec3" }
name = "MeshTangents"
attributes = ["Debuggable"]

[components.mesh_texcoords]
type = { type = "Vec", element_type = "Vec2" }
name = "MeshTexcoords"
attributes = ["Debuggable"]

[components.mesh_indices]
type = { type = "Vec", element_type = "U32" }
name = "MeshIndices"
attributes = ["Debuggable"]

[components.highlight_tile]
type = "Empty"
name = "HighlightTile"
attributes = ["Debuggable"]
description = """
When added to a component with the in_chunk and chunk_tile_index components,
the terrain package will add procedural components to this entity that will
highlight that tile.
"""

[messages.RaycastRequest]
description = """
Send this message to the terrain package to perform a raycast.
The package will respond with RaycastResponse.
"""

[messages.RaycastRequest.fields]
origin = "Vec3"
delta = "Vec3"
limit = "F32"

[messages.RaycastResponse]
description = """
Response to RaycastRequest.
If the ray didn't hit anything, the distance field is set to a negative number.
"""

[messages.RaycastResponse.fields]
collision_pos = "Vec3"
chunk_entity = "EntityId"
chunk_pos = "Ivec2"
tile_idx = "U8"
distance = "F32"
