[package]
id = "terrain"
name = "terrain"
version = "0.0.1"

[dependencies]
map = { path = "../map" }

[components.heightmap]
type = { type = "Vec", element_type = "I16" }
name = "Heightmap"
attributes = ["Debuggable"]
description = """
A list of the heights of all of the tile corners in this chunk.

Because this includes tile corners of tiles in neighboring chunks too, the size
of this list is (CHUNK_SIZE + 1) * (CHUNK_SIZE + 1).

The tiles are ordered X- to X+, then Y- to Y+. For reference:
```
 X----->
Y 0 1 2
| 3 4 5
| 6 7 8
V
```
"""

[components.altitude]
type = "F32"
name = "Altitude"
attributes = ["Debuggable"]
description = "The height of this entity on the map above sea level. Computed using map::position."
