[package]
id = "terrain"
name = "terrain"
version = "0.0.1"

[dependencies]
map = { path = "../map" }

[components.heightmap]
type = { type = "Vec", element_type = "I16" }
name = "Heightmap"
attributes = ["Debuggable"]
description = """
A list of the heights of all of the tile corners in this chunk.

Because this includes tile corners of tiles in neighboring chunks too, the size
of this list is (CHUNK_SIZE + 1) * (CHUNK_SIZE + 1).

The tiles are ordered X- to X+, then Y- to Y+. For reference:
```
 X----->
Y 0 1 2
| 3 4 5
| 6 7 8
V
```
"""

[components.altitude]
type = "F32"
name = "Altitude"
attributes = ["Debuggable"]
description = "The height of this entity on the map above sea level. Computed using map::position."

[messages.RaycastRequest]
description = """
Send this message to the terrain package to perform a raycast.
The package will respond with RaycastResponse.
"""

[messages.RaycastRequest.fields]
origin = "Vec3"
delta = "Vec3"
limit = "F32"

[messages.RaycastResponse]
description = """
Response to RaycastRequest.
If the ray didn't hit anything, the distance field is set to a negative number.
"""

[messages.RaycastResponse.fields]
collision_pos = "Vec3"
chunk_entity = "EntityId"
chunk_pos = "Ivec2"
tile_idx = "U8"
distance = "F32"
