[ember]
id = "flowerpot"
name = "Flowerpot"
version = "0.0.1"

[dependencies]
actions = { path = "core/actions" }
crafting = { path = "core/crafting" }
crops = { path = "core/crops" }
fauna = { path = "core/fauna" }
game = { path = "core/game" }
items = { path = "core/items" }
map = { path = "core/map" }
player = { path = "core/player" }
terrain = { path = "core/terrain" }
ui = { path = "core/ui" }
weather = { path = "core/weather" }
