[ember]
id = "flowerpot"
name = "flowerpot"
version = "0.0.1"

includes = [
  "src/crops/ambient.toml",
  "src/fauna/ambient.toml",
  "src/map/ambient.toml",
  "src/player/ambient.toml",
  "src/terrain/ambient.toml",
  "src/weather/ambient.toml",
]
