[ember]
id = "flowerpot"
name = "Flowerpot"
version = "0.0.1"

[dependencies]
crops = { path = "core/crops" }
fauna = { path = "core/fauna" }
items = { path = "core/items" }
map = { path = "core/map" }
player = { path = "core/player" }
terrain = { path = "core/terrain" }
weather = { path = "core/weather" }
