[workspace]
members = [ "common", "core/*", "utils/*" ]

[workspace.dependencies]
ambient_api = { git = "https://github.com/AmbientRun/Ambient.git", rev = "b3dce07" }
flowerpot-common = { path = "common" }
lazy_static = "1.4"
noise = "0.8"
rapier3d = "0.17"
rustrict = "0.7"
