[package]
id = "crops"
name = "crops"
version = "0.0.1"
content = { type = "Asset", schema = true, code = true }

[dependencies]
map = { path = "../map" }
region_networking = { path = "../../utils/region_networking" }
terrain = { path = "../terrain" }
things = { path = "../../utils/things" }

[components.age]
type = "U16"
name = "GrowthProgress"
attributes = ["Debuggable"]
description = "The age in growth ticks of this crop."

[components.seed]
type = "EntityId"
name = "Seed"
attributes = ["Debuggable"]
description = "The entity ID of the crop class that this crop reproduces into."

[components.seeding_interval]
type = "U16"
name = "SeedingInterval"
attributes = ["Debuggable"]
description = "The age between each attempt at seeding this crop."

[components.next_growth_stage]
type = "EntityId"
name = "NextGrowthStage"
attributes = ["Debuggable"]
description = """
The entity ID of the crop class that this crop grows into.
If null, then the crop is removed from the tile when it grows.
"""

[components.next_growth_age]
type = "U16"
name = "GrowthInterval"
attributes = ["Debuggable"]
description = "The age that this crop needs to reach to grow into its next growth stage."

[components.is_medium_crop]
type = "Empty"
name = "IsMediumCrop"
attributes = ["Debuggable", "Networked"]
description = "A tag for instantiated medium crop entities."

[components.medium_crop_occupant]
type = "EntityId"
name = "MediumCropOccupant"
attributes = ["Debuggable"]
description = "A reference to the medium crop that occupies this tile. Can be null for no occupant."

[components.on_tile]
type = "EntityId"
name = "OnTile"
attributes = ["Debuggable"]
description = "A reference to the tile that this crop is on."

[components.despawn_when_loaded]
type = "EntityId"
name = "DespawnWhenLoaded"
attributes = ["Debuggable"]
description = "An old crop model with a prefab that should be despawned when this entity's prefab is loaded."

[messages.UpdateMediumCrops]
name = "UpdateMediumCrops"
description = "Server-to-client batch update for the medium crops in a chunk."

[messages.UpdateMediumCrops.fields]
chunk = "Ivec2"
crop_classes = { type = "Vec", element_type = "EntityId" }
crop_tiles = { type = "Vec", element_type = "U8" }
