[components.ui]
name = "UI"
description = "Component namespace related to the UI mod."

[messages.request_input]
fields = {}

[messages.release_input]
fields = {}

[messages.join_denied]
fields = { reason = "String" }

[messages.join_request]
name = "JoinRequest"
description = "Client-to-server message to join the game."
fields = { name = "String" }

[messages.accept_join]
fields = {}
