[components.map]
name = "Map"
description = "Map mod-related components."

[components."map::chunk"]
name = "Chunk"
attributes = ["Debuggable"]
type = "Ivec2"
description = "A component given to all chunk entities. Contains its own chunk position."

[components."map::chunk_tile_refs"]
name = "ChunkTileRefs"
type = { type = "Vec", element_type = "EntityId" }
attributes = ["Debuggable"]
description = """
A list of all the tile entities that are part of this tile.

The tiles are ordered X- to X+, then Y- to Y+. For reference:
```
 X----->
Y 0 1 2
| 3 4 5
| 6 7 8
V
```
"""

[messages.load_chunk]
name = "LoadChunk"
description = "Server-to-client message to command a client to load a chunk."
fields = { pos = "Ivec2" }

[messages.unload_chunk]
name = "UnloadChunk"
description = "Server-to-client emssage to command a client to unload a chunk."
fields = { pos = "Ivec2" }

[messages.ready]
name = "Ready"
description = "Client-to-server message sent when the client is ready to receive map data."
fields = {}
