[package]
id = "fauna"
name = "fauna"
version = "0.0.1"
content = { type = "Asset", schema = true, code = true }

[dependencies]
map = { path = "../map" }
nameplate = { path = "../../utils/nameplate" }
terrain = { path = "../terrain" }

[components.is_class]
type = "Empty"
name = "IsClass"
attributes = ["Debuggable", "Networked"]
description = "A tag for networked fauna class entities."

[components.model_prefab_url]
type = "String"
name = "ModelPrefabUrl"
attributes = ["Debuggable", "Networked"]
description = "The asset URL to a model prefab to use for this fauna class."

[components.is_fauna]
type = "Empty"
name = "Fauna"
attributes = ["Debuggable"]
description = "A tag given to all fauna entities."

[components.class]
type = "EntityId"
name = "Class"
attributes = ["Debuggable"]
description = "A reference to the crop class that this crop is an instance of."

[components.pitch]
type = "F32"
name = "Pitch"
attributes = ["Debuggable"]
description = "A fauna's pitch."

[components.yaw]
type = "F32"
name = "Yaw"
attributes = ["Debuggable"]
description = "A fauna's yaw."

[components.name]
type = "String"
name = "Name"
attributes = ["Debuggable"]
description = "This fauna's name. Updated with the UpdateFaunaName message."

[components.is_mod_loaded]
type = "Empty"
name = "IsModLoaded"
attributes = ["Debuggable", "MaybeResource"]
description = """
A resource that is added when the fauna mod has completed loading.
Used to signal to other mods that the client is ready to receive fauna updates.
"""

[messages.UpdateFaunaPosition]
name = "UpdateFaunaPosition"
description = "Updates a fauna's position on the receiving client."
fields = { thing = "EntityId", position = "Vec2" }

[messages.UpdateFaunaPitch]
name = "UpdateFaunaPitch"
description = "Updates a fauna's pitch on the receiving client."
fields = { thing = "EntityId", pitch = "F32" }

[messages.UpdateFaunaYaw]
name = "UpdateFaunaYaw"
description = "Updates a fauna's yaw on the receiving client."
fields = { thing = "EntityId", yaw = "F32" }

[messages.UpdateFaunaName]
name = "UpdateFaunaName"
description = "Updates a fauna's name on the receiving client."
fields = { thing = "EntityId", name = "String" }
