[components.player]
name = "Player"
description = "Component namespace related to the player mod."

[components."player::loaded_chunks"]
type = { type = "Vec", element_type = "Ivec2" }
name = "LoadedChunks"
attributes = ["Debuggable"]
description = "The list of chunk positions that this player currently has loaded."

[components."player::pitch"]
type = "F32"
name = "Pitch"
attributes = ["Debuggable"]
description = "The client-side player's pitch. NOT the player's fauna pitch."

[components."player::yaw"]
type = "F32"
name = "Yaw"
attributes = ["Debuggable"]
description = "The client-side player's yaw. NOT the player's fauna yaw."

[components."player::position"]
type = "Vec2"
name = "Position"
attributes = ["Debuggable"]
description = """
A player's map position.

The client interpolates this with the player's fauna position to implement rubberbanding.

The server uses this in conjunction with the direction component to implement player movement code.
"""

[components."player::speed"]
type = "F32"
name = "Speed"
attributes = ["Debuggable"]
description = "The speed of a player."

[components."player::direction"]
type = "Vec2"
name = "Direction"
attributes = ["Debuggable"]
description = """
The velocity of a player, server-side and client-side.
NOT relative to player yaw.
Maximum length is clamped to 1.0, and use in conjunction with the speed
component to determine the actual player movement.
"""

[components."player::head_ref"]
type = "EntityId"
name = "HeadRef"
attributes = ["Debuggable"]
description = """
A reference to this player's head entity. Used client-side only in order to
update the main camera's transform.
"""

[components."player::left_hand_ref"]
type = "EntityId"
name = "LeftHandRef"
attributes = ["Debuggable"]
description = "A reference to this player's left hand entity."

[components."player::right_hand_ref"]
type = "EntityId"
name = "RightHandRef"
attributes = ["Debuggable"]
description = "A reference to this player's right hand entity."

[components."player::owner_ref"]
type = "EntityId"
name = "OwnerRef"
attributes = ["Debuggable"]
description = "A reference to the player that this entity is owned by."

[components."player::local_player_ref"]
type = "EntityId"
name = "LocalPlayerRef"
attributes = ["Debuggable", "MaybeResource"]
description = "A resource referencing the local player's entity."

[messages.update_player_angle]
name = "UpdatePlayerAngle"
description = "Client-to-server message to update the client's player's angle."
fields = { pitch = "F32", yaw = "F32" }

[messages.update_player_direction]
name = "UpdatePlayerDirection"
description = "Client-to-server message to update the client's player's direction."
fields = { direction = "Vec2" }
