[package]
id = "flowerpot_items"
name = "flowerpot_items"
version = "0.0.1"
content = { type = "Asset", schema = true, code = true }

[dependencies]
player = { path = "../player" }
things = { path = "../../utils/things" }

[components.held_ref]
type = "EntityId"
name = "HeldRef"
attributes = ["Debuggable"]
description = "Attached to a hand entity and references the item instance that the hand is holding. Can be null."

[components.class]
type = "EntityId"
name = "Class"
attributes = ["Debuggable"]
description = "A reference to the item class that this entity is an instance of."

[messages.UpdateHeldItems]
name = "UpdateHeldItems"
description = "Server-to-client message to update the classes of items that the player is holding."
fields = { left = "EntityId", right = "EntityId" }
