[ember]
id = "actions"
name = "actions"
version = "0.0.1"

[messages.register_crafting_action]
name = "RegisterCraftingAction"
description = "Registers a crafting action with the action store."

[messages.register_crafting_action.fields]
primary_held  = "EntityId"
secondary_held  = "EntityId"
id = "String"

[messages.on_crafting_action]
name = "OnCraftingAction"
description = "Sent to the registering module when the registered action is performed."

[messages.on_crafting_action.fields]
player = "EntityId"
id = "String"
right_is_primary = "Bool"

[messages.perform_crafting_action]
name = "PerformCraftingAction"
description = "Client-to-server message to perform a crafting action."
fields = {}
