[ember]
id = "actions"
name = "actions"
version = "0.0.1"

[dependencies]
items = { path = "../items" }
player = { path = "../player" }

[messages.RegisterCraftingAction]
name = "RegisterCraftingAction"
description = "Registers a crafting action with the action store."

[messages.RegisterCraftingAction.fields]
primary_held  = "EntityId"
secondary_held  = "EntityId"
id = "String"

[messages.OnCraftingAction]
name = "OnCraftingAction"
description = "Sent to the registering module when the registered action is performed."

[messages.OnCraftingAction.fields]
id = "String"
player = "EntityId"
right_is_primary = "Bool"

[messages.PerformCraftingAction]
name = "PerformCraftingAction"
description = "Client-to-server message to perform a crafting action."
fields = {}
