[ember]
id = "ui"
name = "ui"
version = "0.0.1"

[components.joined]
type = "Bool"
name = "Joined"
attributes = ["Debuggable", "MaybeResource"]
description = "Client-side resource declaring whether this client has joined the game."

[messages.request_input]
fields = {}

[messages.release_input]
fields = {}

[messages.join_denied]
fields = { reason = "String" }

[messages.join_request]
name = "JoinRequest"
description = "Client-to-server message to join the game."
fields = { name = "String" }

[messages.accept_join]
fields = {}

[messages.announcement]
fields = { content = "String" }

[messages.chat_message]
fields = { author = "String", content = "String" }

[messages.player_message]
fields = { content = "String" }

[messages.chat_denied]
fields = { reason = "String" }
