[ember]
id = "ui"
name = "ui"
version = "0.0.1"

[dependencies]
actions = { path = "../actions" }
fauna = { path = "../fauna" }
player = { path = "../player" }

[components.joined]
type = "Bool"
name = "Joined"
attributes = ["Debuggable", "MaybeResource"]
description = "Client-side resource declaring whether this client has joined the game."

[messages.RequestInput]
fields = {}

[messages.ReleaseInput]
fields = {}

[messages.JoinDenied]
fields = { reason = "String" }

[messages.JoinRequest]
name = "JoinRequest"
description = "Client-to-server message to join the game."
fields = { name = "String" }

[messages.AcceptJoin]
fields = {}

[messages.Announcement]
fields = { content = "String" }

[messages.ChatMessage]
fields = { author = "String", content = "String" }

[messages.PlayerMessage]
fields = { content = "String" }

[messages.ChatDenied]
fields = { reason = "String" }
