[ember]
id = "map"
name = "map"

[components.mod_loaded]
type = "Empty"
name = "ModLoaded"
attributes = ["Debuggable", "MaybeResource"]
description = """
A resource that is added when the map mod has completed loading.
"""

[components.chunk]
name = "Chunk"
attributes = ["Debuggable"]
type = "Ivec2"
description = "A component given to all chunk entities. Contains its own chunk position."

[components.chunk_tile_refs]
name = "ChunkTileRefs"
type = { type = "Vec", element_type = "EntityId" }
attributes = ["Debuggable"]
description = """
A list of all the tile entities that are part of this tile.

The tiles are ordered X- to X+, then Y- to Y+. For reference:
```
 X----->
Y 0 1 2
| 3 4 5
| 6 7 8
V
```
"""

[components.players_observing]
name = "PlayersObserving"
type = { type = "Vec", element_type = "EntityId" }
attributes = ["Debuggable"]
description = """
The list of all players that have loaded this chunk and are observing updates
to it. This list must always be kept sorted so that lists on other chunks may
be rapidly diffed.

This component is automatically updated by the map mod in response to
OnPlayerLoadChunk and OnPlayerUnloadChunk messages, so do not modify this
component directly.
"""

[components.position]
name = "Position"
attributes = ["Debuggable"]
type = "Vec2"
description = "The map position of this entity."

[components.in_chunk]
name = "InChunk"
attributes = ["Debuggable"]
type = "EntityId"
description = "A reference to the chunk that this entity is in. Automatically updated according to its position."

[components.chunk_tile_index]
name = "ChunkTileIndex"
attributes = ["Debuggable"]
type = "U8"
description = "The index of this tile in the parent chunk's tile list."

[components.north_neighbor]
name = "EntityId"
attributes = ["Debuggable"]
type = "EntityId"
description = """
The entity neighboring this entity to the north (-Y).
For chunks, this is another chunk. For tiles, this is another tile.
"""

[components.east_neighbor]
name = "EntityId"
attributes = ["Debuggable"]
type = "EntityId"
description = """
The entity neighboring this entity to the east (+X).
For chunks, this is another chunk. For tiles, this is another tile.
"""

[components.south_neighbor]
name = "EntityId"
attributes = ["Debuggable"]
type = "EntityId"
description = """
The entity neighboring this entity to the south (+Y).
For chunks, this is another chunk. For tiles, this is another tile.
"""

[components.west_neighbor]
name = "EntityId"
attributes = ["Debuggable"]
type = "EntityId"
description = """
The entity neighboring this entity to the west (-X).
For chunks, this is another chunk. For tiles, this is another tile.
"""

[messages.load_chunk]
name = "LoadChunk"
description = "Server-to-client message to command a client to load a chunk."
fields = { pos = "Ivec2" }

[messages.unload_chunk]
name = "UnloadChunk"
description = "Server-to-client emssage to command a client to unload a chunk."
fields = { pos = "Ivec2" }

[messages.load_player_chunk]
name = "LoadPlayerChunk"
description = """
Server-local message commanding the map mod to load a chunk on a player.
The map mod follows this up by broadcasting OnPlayerLoadChunk.
"""

[messages.load_player_chunk.fields]
player_entity = "EntityId"
player_uid = "String"
chunk_pos = "Ivec2"
chunk_entity = "EntityId"

[messages.unload_player_chunk]
name = "UnloadPlayerChunk"
description = """
Server-local message commanding the map mod to unload a chunk on a player.
The map mod follows this up by broadcasting OnPlayerUnloadChunk.
"""

[messages.unload_player_chunk.fields]
player_entity = "EntityId"
player_uid = "String"
chunk_pos = "Ivec2"
chunk_entity = "EntityId"

[messages.on_player_load_chunk]
name = "OnPlayerLoadChunk"
description = "Server-local message emitted after a chunk has been loaded on a player."

[messages.on_player_load_chunk.fields]
player_entity = "EntityId"
player_uid = "String"
chunk_pos = "Ivec2"
chunk_entity = "EntityId"

[messages.on_player_unload_chunk]
name = "OnPlayerUnloadChunk"
description = "Server-local message emitted after a chunk has been unloaded on a player."

[messages.on_player_unload_chunk.fields]
player_entity = "EntityId"
player_uid = "String"
chunk_pos = "Ivec2"
chunk_entity = "EntityId"
