[ember]
id = "crafting"
name = "crafting"
version = "0.0.1"

[components.recipe]
type = "Empty"
name = "Recipe"
attributes = ["Debuggable"]

[components.primary_ingredient]
type = "EntityId"
name = "PrimaryIngredient"
attributes = ["Debuggable"]

[components.secondary_ingredient]
type = "EntityId"
name = "SecondaryIngredient"
attributes = ["Debuggable"]

[components.primary_yield]
type = "EntityId"
name = "PrimaryYield"
attributes = ["Debuggable"]

[components.secondary_yield]
type = "EntityId"
name = "SecondaryYield"
attributes = ["Debuggable"]
